version: '3.5'
services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: "always"
    ports:
     - "15672:15672"
     - "5672:5672"
    network_mode: host

  flower:
    image: mher/flower:0.9.5
    restart: "always"
    network_mode: host
